# exclude SafeMath when calculating test coverage
# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths
reports:
  exclude_contracts:
    - SafeMath
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.5.0
  - smartcontractkit/chainlink@1.4.1
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0'
      - '@chainlink=smartcontractkit/chainlink@1.4.1'
# automatically fetch contract sources from Etherscan
autofetch_sources: True
dotenv: .env
# set a custom mnemonic for the development network
networks:
  default: development
  mainnet:
    openseaProxy: '0xa5409ec958c83c3f309868babaca7c86dcb077c1'
  rinkeby:
    openseaProxy: '0xf57b2c51ded3a29e6891aba85459d600256cf317'
    metadata: 'ipfs://QmPDabUaG1deYEXhDMfCNWq63WqaByNqHDVK5wpPJtUKxR'
    subscriptionId: '123455'
  development:
    openseaProxy: '0xf57b2c51ded3a29e6891aba85459d600256cf317'
    metadata: 'ipfs://QmPDabUaG1deYEXhDMfCNWq63WqaByNqHDVK5wpPJtUKxR'
    subscriptionId: '123455'
    gas_limit: 30000000

wallets:
  from_key: ${PRIVATE_KEY}
  from_mnemonic: ${MNEMONIC}
  # You'd have to change the accounts.add to accounts.from_mnemonic to use from_mnemonic
