bc:
	ganache-cli --accounts 10 --hardfork london --gasLimit 30000000 --mnemonic brownie --port 8545


t:
	brownie test

i:
	brownie test tests --interactive

b:
	brownie compile

.PHONY: bc test build
